# Default values for backup-pvc-cronjob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: debian
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  # runAsUser: 8888

resources:
  limits:
    cpu: 50m
    memory: 300Mi
  requests:
    cpu: 30m
    memory: 150Mi

nodeSelector: {}

tolerations: []

affinity: {}

backupSrcPVC: backup-src-pvc
backupSrcSubdir: '' # replace quotes with path to override
backupDstPVC: backup-dst-pvc
schedule: "30 0 * * 2,3,4,5,6"
retention: 10
