---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.ambassador_service_name }}
  labels:
    # This labels the service as the app 'ambassador' even if the name is something else. It's used
    # to identify that the service is up by tycho, and is useful when the name isn't 'ambassador'.
    app: ambassador
spec:
  type: {{ .Values.service.type }}
  #externalTrafficPolicy: Local
  ports:
   - port: 80
     targetPort: 8080
  selector:
    {{- include "ambassador.selectorLabels" . | nindent 4 }}
