---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.ambassador_service_name }}
spec:
  type: {{ .Values.service.type }}
  #externalTrafficPolicy: Local
  ports:
   - port: 80
     targetPort: 8080
  selector:
    {{- include "ambassador.selectorLabels" . | nindent 4 }}
