# Default values for nfs-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/google_containers/volume-nfs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 0.8

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Specify gcePersistentDiskPdName OR claimName, not both.  If both are specified
# the GCE persistent disk is used for storage.
storage:
  claimName: nfs-server-pvc
  storageClassName:
  pvcStorage: 10Gi
  # gcePersistentDiskPdName:  gce-nfs-server-disk

stdnfs:
  create: true
  pvStorage: 10Gi
  pvcStorage: 10Gi
  pvName: stdnfs-pv
  storageClassName: stdnfs-sc

global:
  stdnfsPvc: stdnfs
