# Parent chart for HeLx.

ambassador:
  # -- enable/disable deployment of Ambassador
  enabled: true
appstore:
  # -- enable/disable deployment of appstore
  enabled: true
backup-pvc-cronjob:
  # -- enable/disable deployment of backup-pvc-cronjob
  enabled: false
image-utils:
  # -- enable/disable deployment of image-utils (imagepullsecret-patcher and
  # imagepuller)
  enabled: false
monitoring:
  # -- enable/disable deployment of monitoring (kube-prometheus-stack,
  # cost-analyzer, etc.)
  enabled: false
nfs-server:
  # -- enable/disable deployment of nfs-server
  enabled: false
nfsrods:
  # -- enable/disable deployment of nfsrods
  enabled: false
nginx:
  # -- enable/disable deployment of nginx
  enabled: true
pod-reaper:
  # -- enable/disable deployment of pod-reaper
  enabled: true
resty:
  # -- enable/disable deployment of nginx
  enabled: false
search:
  # -- enable/disable deployment of search
  enabled: false
tycho-api:
  # -- enable/disable deployment of tycho-api
  enabled: false
ui:
  # -- enable/disable deployment of helx-ui
  enabled: true
appstore-sockets:
  # -- enable/disable deployment of appstore websockets service
  enabled: true

global:
  tycho_api_service_name: helx-tycho-api
  restartr_api_service_name: helx-restartr-api-service
  stdnfsPvc: stdnfs
  redis:
    existingSecret: redis-secret
    existingSecretPasswordKey: redis-password
