{{ if .Values.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nginx-htpasswd
data:
  auth: {{ htpasswd .Values.basicAuth.username .Values.basicAuth.password | b64enc | quote }}
{{ end }}