{{- if not .Values.varStorage.existingClaim }}
{{- if .Values.varStorage.claimName }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.varStorage.claimName }}
  labels:
    app: {{- include "nginx.selectorLabels" . | nindent 6 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.varStorage.storageSize }}
  storageClassName: {{ .Values.varStorage.storageClass }}
{{- end }}
{{- end }}
