# Default values for ambassador.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/datawire/ambassador
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 1.1.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

adminservice:
  type: ClusterIP

securityContext:
  runAsUser: 8888
  # runAsGroup: 8888
  # fsGroup: 8888

resources:
  limits:
    cpu: 300m
    memory: 512Mi
    ephemeral-storage: 512Mi
  requests:
    cpu: 100m
    memory: 200Mi
    ephemeral-storage: 128Mi

ambassador_service_name: ambassador
# -- Specify the Ambassador ID (useful if multiple Ambassadors are deployed to
# the same cluster).
ambassador_id:
