apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup-pvc-cronjob.fullname" . }}-configmap
data:
  backup.sh: |
    #!/bin/bash
    RETENTION_COUNT={{ .Values.retention }}
    TIMESTAMP=`date "+%Y%m%d%H%M"`
    SRC=/backup-src
    BAK=/backup-dst
    echo "backup start: `date`"
    ls -alh $SRC/
    ls -alh $BAK/
    cd $SRC/
    tar -cvzf $BAK/backup-$TIMESTAMP.tar.gz *
    ls -alh $BAK/
    current_backups=(`find $BAK -maxdepth 1 -name 'backup-*.tar.gz' -type f | sort`)
    file_count=`echo "${#sorted_backups[@]}"`
    excess_count=$(($file_count-$RETENTION_COUNT))
    while [ $excess_count -gt 0 ]; do
      echo "Removing Backup: ${sorted_backups[0]}"
      rm `echo "${sorted_backups[0]}"`
      sorted_backups=("${sorted_backups[@]:1}")
      excess_count=$(($excess_count-1))
    done
    echo "backup end: `date`"
