apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "backup-pvc-cronjob.fullname" . }}
  labels:
    {{- include "backup-pvc-cronjob.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backup-pvc-cronjob.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              command: ['/bin/sh']
              args: ['-c', '/backup.sh']
              volumeMounts:
              - name: backup-src-vol
                mountPath: /backup-src
              - name: backup-dst-vol
                mountPath: /backup-dst
              - name: backup-script-vol
                mountPath: /backup.sh
                subPath: backup.sh
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: backup-src-vol
              persistentVolumeClaim:
                claimName: {{ .Values.backupSrcPVC }}
                readOnly: true
            - name: backup-dst-vol
              persistentVolumeClaim:
                claimName: {{ .Values.backupDstPVC }}
            - name: backup-script-vol
              configMap:
                name: {{ include "backup-pvc-cronjob.fullname" . }}-configmap
                defaultMode: 0755
          restartPolicy: Never
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
