apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nfsrods.fullname" . }}
  labels:
    {{- include "nfsrods.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nfsrods.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nfsrods.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["{{ .Values.runArgs }}"]
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: exports-vol
            mountPath: /nfsrods_config/exports
            subPath: exports
          - name: log4j-properties-vol
            mountPath: /nfsrods_config/log4j.properties
            subPath: log4j.properties
          - name: server-json-vol
            mountPath: /nfsrods_config/server.json
            subPath: server.json
      volumes:
        - name: exports-vol
          configMap:
            name: configs-configmap
            defaultMode: 0644
        - name: log4j-properties-vol
          configMap:
            name: configs-configmap
            defaultMode: 0644
        - name: server-json-vol
          configMap:
            name: configs-configmap
            defaultMode: 0644
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
