apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfsrods.fullname" . }}
  labels:
    {{- include "nfsrods.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.nfsPort }}
      targetPort: 2049
      protocol: TCP
      name: nfs
    - port: {{ .Values.service.mountdPort }}
      targetPort: 20048
      name: mountd
    - port: {{ .Values.service.rpcbindPort }}
      targetPort: 111
      name: rpcbind
  selector:
    {{- include "nfsrods.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  # Need to specify IP so that nodes can mount the NFS share.  PVCs need to use
  # the same IP in their YAML.
  clusterIP: {{ .Values.service.ip }}
