{{- if not .Values.storage.gcePersistentDiskPdName }}
{{- if not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace ( .Values.storage.claimName )) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.storage.claimName }}
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.pvcStorage }}
  storageClassName: {{ .Values.storage.storageClassName }}
{{- end }}
{{- end }}
