apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs-server.fullname" . }}
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 2049
      targetPort: 2049
      protocol: TCP
      name: nfs
    - port: 20048
      targetPort: 20048
      protocol: TCP
      name: mountd
    - port: 111
      targetPort: 111
      protocol: TCP
      name: rpcbind
  selector:
    {{- include "nfs-server.selectorLabels" . | nindent 4 }}
