{{ if .Values.stdnfs.create }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.stdnfs.pvName }}
spec:
  capacity:
    storage: {{ .Values.stdnfs.pvStorage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  storageClassName: {{ .Values.stdnfs.storageClassName }}
  nfs:
    path: /
    server: {{ include "nfs-server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.stdnfsPvc }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: {{ .Values.stdnfs.pvcStorage }}
  storageClassName: {{ .Values.stdnfs.storageClassName }}
{{ end }}
