{{- if .Values.ingress.create }}
{{ if .Values.basicAuth.enabled }}
   {{ $_ := set .Values.ingress.annotations "nginx.ingress.kubernetes.io/auth-type" "basic" }}
   {{ $secretName := printf "%s-nginx-htpasswd" .Release.Name}}
   {{ $_ := set .Values.ingress.annotations "nginx.ingress.kubernetes.io/auth-secret" $secretName}}
{{ end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "resty.fullname" . }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
      - "{{ .Values.service.serverName }}"
    secretName: "{{ .Values.SSL.nginxTLSSecret }}"
{{- end}}
  rules:
  - host: "{{ .Values.service.serverName }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "resty.fullname" . }}
            port:
              number: {{ .Values.service.httpPort }}
---
{{- if .Values.ingress.admin.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "resty.fullname" . }}-admin
  {{- with .Values.ingress.admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: "{{ .Values.ingress.ingressClassName }}"
{{- end}}
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
      - "{{ .Values.service.serverName }}"
    secretName: "{{ .Values.SSL.nginxTLSSecret }}"
{{- end}}
  rules:
  - host: "{{ .Values.service.serverName }}"
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: {{ include "resty.fullname" . }}
            port:
              number: {{ .Values.service.httpPort }}
{{- end }}
{{- end }}
