apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
data:
  nginx.conf: |
    user  nginx;

    worker_processes  auto;
    error_log         "/opt/bitnami/openresty/nginx/logs/error.log";
    pid               "/opt/bitnami/openresty/nginx/tmp/nginx.pid";

    events {
      worker_connections  {{ .Values.workerConnections }};
    }


    http {
      log_format main '{ "date_access":"$time_iso8601", '
        '"user_id":"$http_x_userid", '
        '"request_id":"$http_x_reqid", '
        '"session_id":"$http_x_sessionid", '
        '"visitor_id":"$http_x_visitorid", '
        '"network_client_ip":"$http_x_forwarded_for", '
        '"network_bytes_write":$body_bytes_sent, '
        '"response_secs":$request_time, '
        '"http_status_code":$status, '
        '"http_request":"$request_uri", '
        '"http_verb":"$request_method", '
        '"http_referer":"$http_referer", '
        '"http_useragent":"$http_user_agent", '
        '"REMOTE_USER":$http_remote_user", '
        '"message":"$request"'
        '"request_uri":"$request_uri"}';

      include       mime.types;
      default_type  application/octet-stream;
      access_log    "/opt/bitnami/openresty/nginx/logs/access.log" main;
      add_header    X-Frame-Options SAMEORIGIN;

      client_body_temp_path  "/opt/bitnami/openresty/nginx/tmp/client_body" 1 2;
      proxy_temp_path        "/opt/bitnami/openresty/nginx/tmp/proxy" 1 2;
      fastcgi_temp_path      "/opt/bitnami/openresty/nginx/tmp/fastcgi" 1 2;
      scgi_temp_path         "/opt/bitnami/openresty/nginx/tmp/scgi" 1 2;
      uwsgi_temp_path        "/opt/bitnami/openresty/nginx/tmp/uwsgi" 1 2;

      sendfile                  on;
      tcp_nopush                on;
      tcp_nodelay               on;
      gzip                      on;
      gzip_http_version         1.0;
      gzip_comp_level           2;
      gzip_proxied              any;
      gzip_types                text/plain text/css application/javascript text/xml application/xml+rss;
      keepalive_timeout         65;
      ssl_protocols             TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
      ssl_ciphers               HIGH:!aNULL:!MD5;
      client_max_body_size      80M;
      server_tokens             off;

      types_hash_max_size       2048;
      ssl_prefer_server_ciphers on;



      #access_log /var/log/nginx/access.log json;
      #error_log /var/log/nginx/error.log;
      include  "/opt/bitnami/openresty/nginx/conf/conf.d/*.conf";
    }
