# Convenience workflow responsible for adjusting
# Chart.yml 'version' & 'appVersion' fields to the 
# corresponding app:[version-tag]
# and incrementing 'version' field by 1 in the patch section.

# Additionally, helm-docs is run to autogenerate README.md 
# updates and github badges corresponding to new Chart.yml.

# This workflow will uses the github api to get
# latest app release tag information and update 'appVersion' field or 
# will take user input for the appVersion field.
#
# Eg. Chart.yml
#        name: appstore
#        version: 1.7.0    -> 1.7.1 -> 1.7.2
#        appVersion: 2.1.0 -> 2.2.1 -> 3.0.0
#  
#

name: Bump-Chart-Versions
on:
  workflow_dispatch:
    inputs:
      chartVersion:
        description: 'With every change to the helm chart, the chart version and app version will be the same and should be incremented. If unset- patch increments by +1.'
        required: false
        type: string
    
jobs:
  bump-app-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0

    - name: Install yq Utility
      run: | 
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64

    - name: Check chartVersion Inputs
      id: checkChartVersion
      shell: bash
      run: |
        if [ "${{ inputs.chartVersion }}" == "" ]; then
          echo "chartVersionPresent=NO" >> $GITHUB_OUTPUT
        else
          echo "chartVersionPresent=YES" >> $GITHUB_OUTPUT
        fi

    # Awk magic below
    # Ref: https://www.reddit.com/r/bash/comments/78rxyv/how_to_make_awk_return_an_integer/
    # We obtain version major.minor.patch, and always increment patch by 1.
    - name: AutoIncrement Chart Version
      id: autoChartVersion
      run: |
        MAJOR=$(yq '.version' Chart.yaml | awk -F. '{ print $1 }')
        MINOR=$(yq '.version' Chart.yaml | awk -F. '{ print $2 }')
        BUMP_PATCH=$(yq '.version' Chart.yaml | awk -F. '{print int($3) + 1}')
        CHARTVERSION=$(echo $MAJOR.$MINOR.$BUMP_PATCH) yq --inplace '.version = env(CHARTVERSION)' Chart.yaml
        echo "autoChartVersion=$CHARTVERSION" >> $GITHUB_OUTPUT
      if: ( steps.checkChartVersion.outputs.chartVersionPresent == 'NO')

    - name: Set User Specified chart version
      env:
        CHARTVERSION: ${{ inputs.chartVersion }} 
      run: |
        yq --inplace '.version = env(CHARTVERSION)' Chart.yaml
      if: ( steps.checkChartVersion.outputs.chartVersionPresent == 'YES')

    - name: Set User Specified Tag
      env:
        APPVERSION: ${{ inputs.chartVersion }}
      run: |
        yq --inplace '.appVersion = env(APPVERSION)' Chart.yaml
      if: ( steps.checkChartVersion.outputs.chartVersionPresent == 'YES')

    - name: Set Auto Genrated Tag
      env:
        APPVERSION: ${{ steps.autoChartVersion.outputs.autoChartVersion }}
      run: |
        yq --inplace '.appVersion = env(APPVERSION)' Chart.yaml
      if: ( steps.checkChartVersion.outputs.chartVersionPresent == 'NO')


############################# Lint-Test #########################
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.4.0

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Run chart-testing (lint)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct lint --target-branch ${{ github.event.repository.default_branch }}

    - name: Create kind cluster
      if: steps.list-changed.outputs.changed == 'true'
      uses: helm/kind-action@v1.4.0

    - name: Run chart-testing (install)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct install --target-branch ${{ github.event.repository.default_branch }}

############################## Generate Docs and Push ##########################################   
    - name: Download Helm-Docs
      run: |
        wget https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_x86_64.tar.gz
        tar -xvf helm-docs_1.11.0_Linux_x86_64.tar.gz
        mv helm-docs /usr/local/bin/
        chmod +x /usr/local/bin/helm-docs 

    - name: Create Helm-Docs README.md
      run: | 
        helm-docs

    - name: Commit Chart.yaml Changes
      uses: EndBug/add-and-commit@v9
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        author_name: Actions_${{ github.actor}}
        message: 'Bumping appVersion and chart version, updating readme'
        add: 'Chart.yaml README.md'