# This chart catches changes and then pushed to main branch
# Tests, Updates Dependency and Packages, then pushes to 
# our parent repo that holds all Helx Charts Helm-Charts

name: Update-Package-Trigger-Helm-Charts
on:
  push:
    branches:
      - main 
      - master
    paths-ignore:
      - .github/workflows/*
      - .github/*
jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.4.0

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Run chart-testing (lint)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct lint --target-branch ${{ github.event.repository.default_branch }}

    - name: Create kind cluster
      if: steps.list-changed.outputs.changed == 'true'
      uses: helm/kind-action@v1.4.0

    - name: Run chart-testing (install)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct install --target-branch ${{ github.event.repository.default_branch }}


  trigger-helm-charts:
    runs-on: ubuntu-latest
    needs: update-package
    steps:

    - name: Trigger Helm-Charts Workflow
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: | 
        gh --repo https://github.com/helxplatform/helm-charts \
        workflow run package-index.yml \
        -f appRepo=${{ github.repository }} \
        --ref develop